package domain;

// Generated 2016-6-1 14:59:12 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Userstate generated by hbm2java
 */
@Entity
@Table(name = "userstate", catalog = "blog_user")
public class Userstate implements java.io.Serializable {

	private int userId;
	private User user;
	private String password;
	private Date regDate;
	private String regFromIp;
	private boolean online;
	private Date lastLoginTime;
	private String lastLoginFromIp;
	private Date lastChangePsdDate;
	private short changePsdTimes;
	private boolean lockedOut;
	private Date lastLockoutDate;
	private short lockedOutTimes;
	private boolean approved;
	private byte psdAttemptFailCount;
	private String mobile;
	private String email;
	private boolean lockedOff;
	private Date lastLockOffDate;
	private String remark;
	private Integer cn1;
	private String cn2;
	private String cn3;
	private String cn4;
	private String cn5;

	public Userstate() {
	}

	public Userstate(User user, Date regDate, boolean online,
			short changePsdTimes, boolean lockedOut, short lockedOutTimes,
			boolean approved, byte psdAttemptFailCount, boolean lockedOff) {
		this.user = user;
		this.regDate = regDate;
		this.online = online;
		this.changePsdTimes = changePsdTimes;
		this.lockedOut = lockedOut;
		this.lockedOutTimes = lockedOutTimes;
		this.approved = approved;
		this.psdAttemptFailCount = psdAttemptFailCount;
		this.lockedOff = lockedOff;
	}

	public Userstate(User user, String password, Date regDate,
			String regFromIp, boolean online, Date lastLoginTime,
			String lastLoginFromIp, Date lastChangePsdDate,
			short changePsdTimes, boolean lockedOut, Date lastLockoutDate,
			short lockedOutTimes, boolean approved, byte psdAttemptFailCount,
			String mobile, String email, boolean lockedOff,
			Date lastLockOffDate, String remark, Integer cn1, String cn2,
			String cn3, String cn4, String cn5) {
		this.user = user;
		this.password = password;
		this.regDate = regDate;
		this.regFromIp = regFromIp;
		this.online = online;
		this.lastLoginTime = lastLoginTime;
		this.lastLoginFromIp = lastLoginFromIp;
		this.lastChangePsdDate = lastChangePsdDate;
		this.changePsdTimes = changePsdTimes;
		this.lockedOut = lockedOut;
		this.lastLockoutDate = lastLockoutDate;
		this.lockedOutTimes = lockedOutTimes;
		this.approved = approved;
		this.psdAttemptFailCount = psdAttemptFailCount;
		this.mobile = mobile;
		this.email = email;
		this.lockedOff = lockedOff;
		this.lastLockOffDate = lastLockOffDate;
		this.remark = remark;
		this.cn1 = cn1;
		this.cn2 = cn2;
		this.cn3 = cn3;
		this.cn4 = cn4;
		this.cn5 = cn5;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@JsonIgnore
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "password", length = 256)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "regDate", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "regFromIp", length = 128)
	public String getRegFromIp() {
		return this.regFromIp;
	}

	public void setRegFromIp(String regFromIp) {
		this.regFromIp = regFromIp;
	}

	@Column(name = "online", nullable = false)
	public boolean isOnline() {
		return this.online;
	}

	public void setOnline(boolean online) {
		this.online = online;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastLoginTime", length = 19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "lastLoginFromIp", length = 128)
	public String getLastLoginFromIp() {
		return this.lastLoginFromIp;
	}

	public void setLastLoginFromIp(String lastLoginFromIp) {
		this.lastLoginFromIp = lastLoginFromIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastChangePsdDate", length = 19)
	public Date getLastChangePsdDate() {
		return this.lastChangePsdDate;
	}

	public void setLastChangePsdDate(Date lastChangePsdDate) {
		this.lastChangePsdDate = lastChangePsdDate;
	}

	@Column(name = "changePsdTimes", nullable = false)
	public short getChangePsdTimes() {
		return this.changePsdTimes;
	}

	public void setChangePsdTimes(short changePsdTimes) {
		this.changePsdTimes = changePsdTimes;
	}

	@Column(name = "lockedOut", nullable = false)
	public boolean isLockedOut() {
		return this.lockedOut;
	}

	public void setLockedOut(boolean lockedOut) {
		this.lockedOut = lockedOut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastLockoutDate", length = 19)
	public Date getLastLockoutDate() {
		return this.lastLockoutDate;
	}

	public void setLastLockoutDate(Date lastLockoutDate) {
		this.lastLockoutDate = lastLockoutDate;
	}

	@Column(name = "lockedOutTimes", nullable = false)
	public short getLockedOutTimes() {
		return this.lockedOutTimes;
	}

	public void setLockedOutTimes(short lockedOutTimes) {
		this.lockedOutTimes = lockedOutTimes;
	}

	@Column(name = "approved", nullable = false)
	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	@Column(name = "psdAttemptFailCount", nullable = false)
	public byte getPsdAttemptFailCount() {
		return this.psdAttemptFailCount;
	}

	public void setPsdAttemptFailCount(byte psdAttemptFailCount) {
		this.psdAttemptFailCount = psdAttemptFailCount;
	}

	@Column(name = "mobile", length = 16)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "email", length = 256)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "lockedOff", nullable = false)
	public boolean isLockedOff() {
		return this.lockedOff;
	}

	public void setLockedOff(boolean lockedOff) {
		this.lockedOff = lockedOff;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastLockOffDate", length = 19)
	public Date getLastLockOffDate() {
		return this.lastLockOffDate;
	}

	public void setLastLockOffDate(Date lastLockOffDate) {
		this.lastLockOffDate = lastLockOffDate;
	}

	@Column(name = "remark", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "cn1")
	public Integer getCn1() {
		return this.cn1;
	}

	public void setCn1(Integer cn1) {
		this.cn1 = cn1;
	}

	@Column(name = "cn2", length = 512)
	public String getCn2() {
		return this.cn2;
	}

	public void setCn2(String cn2) {
		this.cn2 = cn2;
	}

	@Column(name = "cn3", length = 512)
	public String getCn3() {
		return this.cn3;
	}

	public void setCn3(String cn3) {
		this.cn3 = cn3;
	}

	@Column(name = "cn4", length = 512)
	public String getCn4() {
		return this.cn4;
	}

	public void setCn4(String cn4) {
		this.cn4 = cn4;
	}

	@Column(name = "cn5", length = 512)
	public String getCn5() {
		return this.cn5;
	}

	public void setCn5(String cn5) {
		this.cn5 = cn5;
	}

	@Override
	public String toString() {
		return "Userstate [userId=" + userId + ", password="
				+ password + ", regDate=" + regDate + ", regFromIp="
				+ regFromIp + ", online=" + online + ", lastLoginTime="
				+ lastLoginTime + ", lastLoginFromIp=" + lastLoginFromIp
				+ ", lastChangePsdDate=" + lastChangePsdDate
				+ ", changePsdTimes=" + changePsdTimes + ", lockedOut="
				+ lockedOut + ", lastLockoutDate=" + lastLockoutDate
				+ ", lockedOutTimes=" + lockedOutTimes + ", approved="
				+ approved + ", psdAttemptFailCount=" + psdAttemptFailCount
				+ ", mobile=" + mobile + ", email=" + email + ", lockedOff="
				+ lockedOff + ", lastLockOffDate=" + lastLockOffDate
				+ ", remark=" + remark + ", cn1=" + cn1 + ", cn2=" + cn2
				+ ", cn3=" + cn3 + ", cn4=" + cn4 + ", cn5=" + cn5 + "]";
	}
	
	

}
