package domain;

// Generated 2016-6-1 14:59:12 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Userdetail generated by hbm2java
 */
@Entity
@Table(name = "userdetail", catalog = "blog_user")
public class Userdetail implements java.io.Serializable {

	private int userId;
	private User user;
	private boolean showDetails;
	private String nickname;
	private String motto;
	private Character sex;
	private Date birthday;
	private String constellation;
	private String address;
	private String region;
	private String wechat;
	private String qq;
	private String portrait;
	private String remark;
	private Integer cn1;
	private String cn2;
	private String cn3;
	private String cn4;
	private String cn5;

	public Userdetail() {
	}

	public Userdetail(User user, boolean showDetails) {
		this.user = user;
		this.showDetails = showDetails;
	}

	public Userdetail(User user, boolean showDetails, String nickname,
			String motto, Character sex, Date birthday, String constellation,
			String address, String region, String wechat, String qq,
			String portrait, String remark, Integer cn1, String cn2,
			String cn3, String cn4, String cn5) {
		this.user = user;
		this.showDetails = showDetails;
		this.nickname = nickname;
		this.motto = motto;
		this.sex = sex;
		this.birthday = birthday;
		this.constellation = constellation;
		this.address = address;
		this.region = region;
		this.wechat = wechat;
		this.qq = qq;
		this.portrait = portrait;
		this.remark = remark;
		this.cn1 = cn1;
		this.cn2 = cn2;
		this.cn3 = cn3;
		this.cn4 = cn4;
		this.cn5 = cn5;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
	
	@JsonIgnore
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "showDetails", nullable = false)
	public boolean isShowDetails() {
		return this.showDetails;
	}

	public void setShowDetails(boolean showDetails) {
		this.showDetails = showDetails;
	}

	@Column(name = "nickname", length = 128)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "motto", length = 256)
	public String getMotto() {
		return this.motto;
	}

	public void setMotto(String motto) {
		this.motto = motto;
	}

	@Column(name = "sex", length = 1)
	public Character getSex() {
		return this.sex;
	}

	public void setSex(Character sex) {
		this.sex = sex;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "constellation", length = 64)
	public String getConstellation() {
		return this.constellation;
	}

	public void setConstellation(String constellation) {
		this.constellation = constellation;
	}

	@Column(name = "address", length = 256)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "region", length = 256)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "wechat", length = 256)
	public String getWechat() {
		return this.wechat;
	}

	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	@Column(name = "qq", length = 64)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "portrait", length = 256)
	public String getPortrait() {
		return this.portrait;
	}

	public void setPortrait(String portrait) {
		this.portrait = portrait;
	}

	@Column(name = "remark", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "cn1")
	public Integer getCn1() {
		return this.cn1;
	}

	public void setCn1(Integer cn1) {
		this.cn1 = cn1;
	}

	@Column(name = "cn2", length = 512)
	public String getCn2() {
		return this.cn2;
	}

	public void setCn2(String cn2) {
		this.cn2 = cn2;
	}

	@Column(name = "cn3", length = 512)
	public String getCn3() {
		return this.cn3;
	}

	public void setCn3(String cn3) {
		this.cn3 = cn3;
	}

	@Column(name = "cn4", length = 512)
	public String getCn4() {
		return this.cn4;
	}

	public void setCn4(String cn4) {
		this.cn4 = cn4;
	}

	@Column(name = "cn5", length = 512)
	public String getCn5() {
		return this.cn5;
	}

	public void setCn5(String cn5) {
		this.cn5 = cn5;
	}

	@Override
	public String toString() {
		return "Userdetail [userId=" + userId
				+ ", showDetails=" + showDetails + ", nickname=" + nickname
				+ ", motto=" + motto + ", sex=" + sex + ", birthday="
				+ birthday + ", constellation=" + constellation + ", address="
				+ address + ", region=" + region + ", wechat=" + wechat
				+ ", qq=" + qq + ", portrait=" + portrait + ", remark="
				+ remark + ", cn1=" + cn1 + ", cn2=" + cn2 + ", cn3=" + cn3
				+ ", cn4=" + cn4 + ", cn5=" + cn5 + "]";
	}
	
	

}
